config/routes.rb
Rails.application.routes.draw do

    resources :post2s
    resources :communities
    resources :posts
    resources :posts do
    resources :favorites, shallow: true, only: [:create, :destroy]
    resources :comments
  end

  resources :users do

  end

  resource :session, only: [:new, :create, :destroy]

  get '/locations/astoria' => 'locations#astoria'
  get '/locations/eastvillage' => 'locations#eastvillage'
  get '/locations/manhattan' => 'locations#manhattan'

  root 'posts#index'
  get 'welcome/about' => 'welcome#about'

  get '*path' => redirect('/')

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy

  validates :username, presence: true
  validates :email, presence: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many(:favorite_posts, {through: :favorites, source: :post})

  has_attached_file :avatar, styles: {
		med: "200x200#",
	}

  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :fetch_user, only: :show

  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_path

    else
      flash[:message]=@user.errors.full_messages.to_sentence
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @user.to_json(include: :favorite_posts) }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private
  def fetch_user
    @user = User.includes(:posts, favorites: :post).find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="new-user-div">

  <h5> Sign Up </h5>

<%= form_for @user do |u| %>

  <%= u.text_field :username, :placeholder => "USERNAME" %> <br>

  <%= u.email_field :email, :placeholder => "EMAIL" %> <br>

  <%= u.password_field :password, :placeholder => "PASSWORD" %> <br>

  <%= u.password_field :password_confirmation, :placeholder => "CONFIRM PASSWORD" %> <br><br>

  <div class="file-field">
  <input class="file-path" type="text" placeholder="Add avatar" id="image-hover"/>
  <input type="file" name="user[avatar]"/>
  </div>

  <!-- <%= u.file_field :avatar %> -->

<br>
<%= u.submit %>
<% end %>

</div>

app/views/users/new.html.erb
<div id="new-user-div">

  <h5> Sign Up </h5>

<%= form_for @user do |u| %>

  <%= u.text_field :username, :placeholder => "USERNAME" %> <br>

  <%= u.email_field :email, :placeholder => "EMAIL" %> <br>

  <%= u.password_field :password, :placeholder => "PASSWORD" %> <br>

  <%= u.password_field :password_confirmation, :placeholder => "CONFIRM PASSWORD" %> <br><br>

  <div class="file-field">
  <input class="file-path" type="text" placeholder="Add avatar" id="image-hover"/>
  <input type="file" name="user[avatar]"/>
  </div>

  <!-- <%= u.file_field :avatar %> -->

<br>
<%= u.submit %>
<% end %>

</div>

app/views/users/show.html.erb
<% if @user === current_user %>
<!-- User Profile -->
<div id="profile-div" class="profile-div">
<% if current_user.avatar? %>
<div id="avatar-image"><%= image_tag @user.avatar.url() %></div>
  <%else%>
<img src="https://myspace.com/common/images/user.png" class="no-photo">
  <%end%>
  <div class="username-show">
  <h6><%= @user.username %></h6>
</div>
</div>

<!-- Map -->
<div id="map-user-mobile">
<div id="map_canvas" style="width: 500x; height: 400px; margin-top: -40px;"></div>
</div>
<br>
<% if @user.favorite_posts.length == 0 %>
<div class="community-explaination">
  <p> You haven't added any posts to your profile yet!<br> Please head back to the main page and add some. Then check back here :)<p>
</div>
<% end%>

<div id="show">
  <hr>
<!-- Posts -->
    <% @user.favorites.each do |favorite| %>
    <% post = favorite.post %>
    <div class="<%=post.title.gsub(/\s+/, "")[0..10]%>">

    <!-- Title -->
    <div id="post-title">
    <h2> <a href="/posts/<%=post.id%>"><%= post.title %></a> </h2>
    </div>

    <!-- Meta -->
    <p><span>	<%= post.created_at.to_date %> <i class="fa fa-circle">
    </i> by <%= post.user.username %> <i class="fa fa-circle">
    </i> <a href="/posts/<%=post.id%>/#comments">Comments <%=post.comments.length %></a> <i class="fa fa-circle"></i></span>
    					<a href="/locations/<%=post.location.downcase.split.join("")%>"><%= post.location %></a><p>


    <!-- Photos -->
    <% post.attachments.each do |image| %>
    	<div id="image-div"><%= image_tag image.url() %></div>
    <% end %>

    <!-- Content -->
    <p> <%= post.content %> <br><br>

    <!-- Delete -->
  <%= button_to 'Delete', favorite_path(favorite), method: :delete %>
  <a href="#.profile-div">Back To Top</a>
  <hr>
  <% end %>
</div>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
   </script>
   <script type="text/javascript">
     var map;
     function initialize() {
       var mapOptions = {
         center: new google.maps.LatLng(40.776093, -73.960562),
         zoom: 11,
         scrollwheel: false,
         mapTypeId: google.maps.MapTypeId.ROADMAP
       };
       map = new google.maps.Map(document.getElementById("map_canvas"),
           mapOptions);
     }
   </script>


<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
 <body onload="initialize()">
   <div id="map_canvas" style="width:100%; height:100%"></div>
   <script type="text/javascript">
   var currentUserId = <%=current_user.id%>
   console.log(currentUserId)
     $(document).ready(function() {
       $.getJSON("/users/" + currentUserId + ".json", function(json1) {
         var favPosts = json1.favorite_posts

         $.each(favPosts, function(key, data) {
           var mapData = data.maps.toString()
           var postTitle = data.title.toString()
           var postLink = postTitle.replace(/\s+/g, '').substring(0,11);;
           console.log(postTitle)
           console.log(postLink);

           var stringLocation = mapData.substring(1, mapData.length-1);
           var lat = stringLocation.split(" ");
            var lat1 = lat[0]
            var long1 = lat[1]
            var long2 = parseFloat(long1)
            var lat2 = parseFloat(lat1)
            console.log(lat2)
            console.log(long2)

            var contentString = '<a href="' + '#.' + postLink + '">' + postTitle + '</a>';

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });




           var latLng = new google.maps.LatLng(lat2, long2);
           // Creating a marker and putting it on the map
           var marker = new google.maps.Marker({
               position: latLng,

           });
           google.maps.event.addListener(marker, 'click', function() {
    infowindow.open(map,marker);
  });
           marker.setMap(map);
         });
       });
     });


               var $root = $('html, body');

          $('#scroll-button').click(function() {
           $root.animate({
               scrollTop: $("#scroll-button").offset().top
           }, 250);
           return false;
          });

   </script>
   <% elsif %>
   <div id="show">
   <h4> Dang.. You're in some restricted stuff! <br> You can only view our own profile...</h4>
   <span class="favorite-link">
   <%= link_to 'Back', '/' %>
   </span>
   </div>
<% end %>