config/routes.rb
Rails.application.routes.draw do

    resources :post2s
    resources :communities
    resources :posts
    resources :posts do
    resources :favorites, shallow: true, only: [:create, :destroy]
    resources :comments
  end

  resources :users do

  end

  resource :session, only: [:new, :create, :destroy]

  get '/locations/astoria' => 'locations#astoria'
  get '/locations/eastvillage' => 'locations#eastvillage'
  get '/locations/manhattan' => 'locations#manhattan'

  root 'posts#index'
  get 'welcome/about' => 'welcome#about'

  get '*path' => redirect('/')

end

app/models/post.rb
class Post < ActiveRecord::Base
  LOCATIONS = ["Manhattan", "Brooklyn", "Queens", "Staten Island", "Bronx", "Westchester", "Hoboken", "Jersey City"]

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_attached_file :image, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}
  has_attached_file :image1, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}
  has_attached_file :image2, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}
  has_attached_file :image3, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}
  has_attached_file :image4, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}
  has_attached_file :image5, styles: {
		small: "64x64",
		med: "200x200",
		large: "800x800"
	}

  validates :location, inclusion: { in: LOCATIONS }


	# Validate the attached image is image/jpg, image/png, etc
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image1, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image2, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image3, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image4, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :image5, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def attachments
    [:image, :image1, :image2, :image3, :image4, :image5].map do |assn|
      self.try(assn)
    end.reject do |img|
      img.url.include? "missing.png"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_current_user, only: :new


  def index
		@posts = Post.all
	end

  def new
    @post = Post.new
  end

  def show
    @post = Post.all
    @favorite = Favorite.all
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @post }
end
  end
  #
  # def create
  #   @post = current_user.posts.new(post_params)
  #
 # 		if @post.save
 # 			redirect_to root_url
 # 		else
 # 			render :new
 # 		end
 # 	end


  def create
  @post = current_user.posts.new(post_params)

  respond_to do |format|
    if @post.save
      format.html  { redirect_to(@post,
                    :notice => 'Post was successfully created.') }
      format.json  { render :json => @post,
                    :status => :created, :location => @post }
    else
      format.html  { render :action => "new" }
      format.json  { render :json => @post.errors,
                    :status => :unprocessable_entity }
    end
  end
end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html  { redirect_to(@post,
                      :notice => 'Post was successfully updated.') }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @post.errors,
                      :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
  end
end

  private

 	def post_params
 		params.require(:post).permit(:title, :image, :image1, :image2, :image3, :image4, :image5, :content, :location, :maps)
 	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<p>Title:</p>
<p><%= comment.name %></p>


<p>Content:</p>
<p><%= comment.content %></p>

<% if comment.user == current_user %> 
	<%= link_to 'Delete comment', [comment.post, comment], method: :delete %>
<% end %>
<hr>

app/views/posts/_form.html.erb
<div id="new-post">
<%= form_for @post do |f| %>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<div id="map"></div>
<br>

    	<%= f.text_field :title, :placeholder => "Title" %> <br>
      <%= f.text_area :content, :placeholder => "Type here..." %> <br>

      <div class="input-field col s12">
      <%= f.select :location, Post::LOCATIONS %>
      </div>
      <br>

      <!-- <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image]"/>
      </div>

      <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image1]"/>
      </div>

      <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image2]"/>
      </div>

      <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image3]"/>
      </div>

      <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image4]"/>
      </div>

      <div class="file-field">
      <input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
      <input type="file" name="post[image5]"/>
      </div><br> -->

     <input type="hidden" name="post[maps]" id="latlngfield">
    <input type="submit" name="commit" id="submitbutton" value="Submit Data">
<% end %>
</div>

app/views/posts/edit.html.erb
<% if current_user.id === @post.user_id %>
<div class="post-create-explaination">
	<p> Currently, editing does not support file uploads. Please compose a new post if you require additional photographs. Additionally, don't forget to update the location via Google Maps. <p>
</div>
<%= render 'form' %>

<div id="show">
	<span class="favorite-link">
<%= link_to 'Back', @post %>
</span>
<span class="favorite-link">
<%= link_to 'Delete Post', @post, :confirm => 'Are you sure?',
																		:method => :delete %>
																	</span>
																	</div>
<% elsif %>
<div id="show">
<h4> Whoops! You can't edit a post you haven't authored.</h4>
<span class="favorite-link">
<%= link_to 'Back', @post %>
</span>
</div>
																		<% end %>

app/views/posts/index.html.erb
<div id="show">
	<% @posts.sort{ |a,b| b.created_at <=> a.created_at }.each do |post| %>
		<!-- title -->
		<div id="post-title">
			<h2><a href="/posts/<%=post.id%>"><%= post.title %></a></h2>
		</div>
		<!-- meta -->
		<p>
			<span><%= post.created_at.to_date %>
				<i class="fa fa-circle"></i> by <%= post.user.username %>
				<i class="fa fa-circle"></i> <a href="/posts/<%=post.id%>/#comments">Comments <%=post.comments.length %></a>
				<i class="fa fa-circle"></i>
			</span>
			<a href="/locations/<%=post.location.downcase.split.join("")%>"><%= post.location %></a>
		<p>
		<!-- photos -->
		<% post.attachments.each do |image| %>
			<div class="image-div"><%= image_tag image.url %></div><br>
		<% end %>
		<p><%= post.content %></p>
			<hr>
	<% end %>
</div>

app/views/posts/new.html.erb
<% if current_user.is_featured == true%>
<div class="post-create-explaination">
  <p> Welcome to posting! Use the map below to choose the location of your post. We currently support up to six photographs per post. Additionaly, don't forget to mark what borough the post is referencing! Thanks and enjoy. - B&B <p>
</div>
<div id="new-post">
<%= form_for @post do |f| %>

<!-- Google Maps Api! -->
<!-- <div id="map-canvas"></div> -->

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<div id="map-container">
<div id="map"></div>
</div>
<br>

<style>
$(document).ready(function() {
    $('select').material_select();
});
</style>

<!-- Title -->
<!-- <%= f.label :title %> -->
<%= f.text_field :title, :placeholder => "Title" %> <br>
<!-- Author -->

<!-- Content -->
<!-- <%= f.label :content %><br> -->
<%= f.text_area :content, :placeholder => "Type here..." %> <br>

<!-- Location -->
<!-- <%= f.label :Location %> -->
<div class="input-field col s12">
<%= f.select :location, Post::LOCATIONS %>
</div>
<br>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image]"/>
</div>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image1]"/>
</div>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image2]"/>
</div>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image3]"/>
</div>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image4]"/>
</div>

<div class="file-field">
<input class="file-path" type="text" placeholder="Add image" id="image-hover"/>
<input type="file" name="post[image5]"/>
</div>



<!-- <%= f.file_field :image %> <br>
<%= f.label :image1 %>
<%= f.file_field :image1 %> <br>
<%= f.label :image2 %>
<%= f.file_field :image2 %> <br>
<%= f.label :image3 %>
<%= f.file_field :image3 %> <br>
<%= f.label :image4 %>
<%= f.file_field :image4 %> <br>
<%= f.label :image5 %>
<%= f.file_field :image5 %> <br>      <br> -->

<input type="hidden" name="post[maps]" id="latlngfield">
<!-- <%= f.submit %> -->
    <input type="submit" name="commit" id="submitbutton" value="Submit Data">
<% end %>
</div>
<%elsif%>
<div id="show">
<h4> Whoops! Looks like you're a bit lost. If you're looking to create a post, head to the Community section!</h4>
<span class="favorite-link">
<%= link_to 'Back', @post %>
</span>
<span class="favorite-link">
<%= link_to 'Community', post2s_path %>
</span>
</div>
<%end%>

app/views/posts/show.html.erb
<style>
	.slider {
		margin-top: -40px;
	}
</style>
<div class="slider">
    <ul class="slides">
			<% @post.attachments.each do |image| %>
      <li>
        <%= image_tag image.url() %> <!-- random image -->
        <div class="caption center-align">
          <!-- <h3>This is our big Tagline!</h3> -->
          <!-- <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5> -->
        </div>
      </li>
		<% end %>
    </ul>
  </div>

<div class="show-padding">
<div class="row">
<div class="col s12 l8" style="margin-bottom: 10px;">
<h5> <%= @post.title %>
<!-- <span class="favorite-link">
<% if current_user && !@favorite.exists?(user_id: current_user.id, post_id: @post.id) %>
<%= link_to 'Add to profile', post_favorites_path(@post), method: :post %>
<% end %>
</span> -->
</h5>

<h1 class="location"> <%= @post.maps %> </h1>

<!-- # <% @post.attachments.each do |image| %>
# 	<div id="image-div"><%= image_tag image.url() %></div><br>
# <% end %> -->

<p> <%= @post.content %> <p>
	<% if current_user && !@favorite.exists?(user_id: current_user.id, post_id: @post.id) %>
		<span class="favorite-link">
	<%= link_to 'Add to profile', post_favorites_path(@post), method: :post %>
	<% elsif current_user  %>
	<a href="/users/<%=current_user.id %>"><i class="fa fa-heart-o"></i></a>
	<% end %>
	</span>

	<% if current_user === @post.user %>
		<span class="favorite-link">
	<%= link_to 'Edit Post', edit_post_path(@post) %><%end%>
</span>
</div>

<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<div class="col s12 l4">
<div id="map-show" style="width: 500x; height: 300px; margin-top: 25px;"></div>
<br><br>
</div>

<% if current_user %>
<div id="comments" class="comment-box col s12 l8">
	<p>Comment below:</p>
	<%= form_for([@post, @post.comments.build]) do|f| %>
		<p>
			<%= f.text_area :content %>
		</p>
		<%= f.submit %>
	<% end %>
</div>
<%end%>

<div class="comments col s12 l8">
<hr>
	<% @post.comments.each do |comment| %>

		<div id="comment">
			<% if comment.content %>
			<p><%= comment.content %></p>
				<p style="text-align: right; color: lightgrey;">by <span><%= comment.name %></span><i class="fa fa-circle"></i><%= comment.created_at %>
					<% end %>
		<% if current_user && current_user.username === comment.name %><i class="fa fa-circle"></i>
				<%= link_to 'Delete comment', [comment.post, comment], method: :delete %>
				<%end%>
			</div>
		<% end %>
		</div>
	</div>
	<!-- <% if current_user && !@favorite.exists?(user_id: current_user.id, post_id: @post.id) %>
	<%= link_to 'Favorite', post_favorites_path(@post), method: :post %>
	<% end %> -->




</div>

<!-- <h2> <%= @post.content %> </h2> -->

<!-- <div class="comments">
	<h4>Comments</h4>
	<%= render partial: "comment", collection: @post.comments, locals: {current_user: @current_user} %>
</div>
<div class="comment-box">
	<h4>Comment below:</h4>
	<%= form_for([@post, @post.comments.build]) do|f| %>
		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.label :content %><br>
			<%= f.text_area :content %>
		</p>
		<%= f.submit %>
	<% end %>
</div> -->

<!-- IF CURRENT USER  -->
<!-- <% if current_user === @post.user %>
<%= link_to 'Edit', edit_post_path(@post) %><%end%> -->


<script>
// var home = <%=@post.maps %>
// console.log("Var home " + home);

 var mapLocation = $('.location').html().toString()
 var stringLocation = mapLocation.substring(2, mapLocation.length-2)
 var lat = stringLocation.split(" ")
 var lat1 = lat[0]
 var long1 = lat[1]
 var long2 = parseFloat(long1)
 var lat2 = parseFloat(lat1)
 console.log(long2)
 console.log(lat2)
 console.log(stringLocation)

var myLatlng = new google.maps.LatLng(lat2,long2);
var mapOptions = {
  zoom: 13,
	scrollwheel: false,
  center: myLatlng
}
var map = new google.maps.Map(document.getElementById("map-show"), mapOptions);
var marker = new google.maps.Marker({
    position: myLatlng,
    title:"Hello World!"
});
// To add the marker to the map, call setMap();
marker.setMap(map);
$(document).ready(function(){
      $('.slider').slider({full_width: true, height: 400});
    });
	</script>